"""
Symmetry reduction for the cyclopentadienyl anion (Cp-): 5 orbitals, 6 electrons,
aromatic pi-system isoelectronic with benzene's pi-system.

The symvb-representable subgroup of D_5h acting on the pi-only basis is
C_5 + sigma_v (order 10); sigma_h is trivial on a pi-only basis, and the
C_2' axes / S_5 operations are generated by C_5 compositions with sigma_v.

Reduction chain (orthogonal-AO Huckel limit, s=0):

    100   (full Sz = 0 FCI, C(5,3)^2)
     |   C_5 + sigma_v
     ?    A_1'
     |   S^2 = 0  (singlet)
     ?    singlet-A_1'   <-- contains the ground state at U > 0

No eta-pairing reduction: the pentagon is an odd cycle, not bipartite,
so no sublattice sign pattern exists and eta_+ does not close as a
symmetry of the kinetic Hamiltonian.

Compare to benzene (even cycle, bipartite):
    400 -> 38 (A_1g) -> 22 (singlet) -> 14 (singlet, eta=0)
"""
import time
import numpy as np
import sympy as sp
from collections import Counter

from symvb import Molecule, SlaterDet, symmetry
from symvb.spin import s_squared_matrix


ORBS = list('abcde')


def deg_hist(ev, tol=1e-6):
    s = sorted(ev.tolist())
    out, i = [], 0
    while i < len(s):
        j = i + 1
        while j < len(s) and abs(s[j] - s[i]) < tol:
            j += 1
        out.append(j - i)
        i = j
    return Counter(out)


def build_basis():
    # Pentagon connectivity: ab, bc, cd, de, ae
    m = Molecule(zero_ii=True,
                 subst={'s': ('S_ab', 'S_bc', 'S_cd', 'S_de', 'S_ae'),
                        'h': ('H_ab', 'H_bc', 'H_cd', 'H_de', 'H_ae')},
                 interacting_orbs=['ab', 'bc', 'cd', 'de', 'ae'])
    m.generate_basis(3, 3, 5)
    det_strings = [fp.dets[0].det_string for fp in m.basis]
    return m, det_strings


def a1_projector(det_strings):
    """Totally-symmetric (A_1') block under C_5 + sigma_v."""
    def canon(ds):
        fp = SlaterDet(ds).get_sorted()
        return fp.dets[0].det_string, fp.coefs[0]

    # C_5:  a -> b -> c -> d -> e -> a
    C5    = {'a': 'b', 'b': 'c', 'c': 'd', 'd': 'e', 'e': 'a'}
    # sigma_v through 'a' and the midpoint of cd:  a fixed, b<->e, c<->d
    sigma = {'a': 'a', 'b': 'e', 'c': 'd', 'd': 'c', 'e': 'b'}

    perms = [symmetry.apply_orbital_permutation(om, det_strings, canon)[0]
             for om in (C5, sigma)]
    U_a, orbits = symmetry.totally_symmetric_basis(perms, len(det_strings))
    return U_a, orbits


def double_occ(ds):
    occ = {}
    for c in ds:
        occ.setdefault(c.lower(), [False, False])
        if c.islower():
            occ[c.lower()][0] = True
        else:
            occ[c.lower()][1] = True
    return sum(1 for ab in occ.values() if ab[0] and ab[1])


def main():
    print('Building Cp- FCI basis (3 alpha + 3 beta in 5 orbitals)...')
    m, det_strings = build_basis()
    N = len(det_strings)
    print(f'  N = {N} dets at Sz = 0   [expected C(5,3)^2 = 100]')

    print('\nBuilding S^2 matrix...')
    t0 = time.time()
    S2 = s_squared_matrix(det_strings)
    print(f'  done in {time.time()-t0:.2f}s')

    # --- A_1' symmetry projection ---------------------------------------
    print('\nBuilding C_5 + sigma_v A_1 projector...')
    U_a, orbits = a1_projector(det_strings)
    print(f'  A_1 dim = {U_a.shape[1]}   (orbit count under order-10 group)')
    print(f'  orbit-size histogram: {dict(sorted(Counter(len(o) for o in orbits).items()))}')

    # --- symbolic H at orthogonal-AO point ------------------------------
    # (S is the identity at s = 0, so only the one-electron H is needed here)
    print('\nSymbolic H over the determinantal basis...')
    t0 = time.time()
    H_sym = m.build_matrix(m.basis, op='H')
    print(f'  done in {time.time()-t0:.2f}s')
    h, s = sp.symbols('h s')

    H0 = np.array(H_sym.subs({h: -1, s: 0}).tolist(), dtype=float)

    # --- project onto A_1 ------------------------------------------------
    H_a = U_a.T @ H0 @ U_a
    S2_a = U_a.T @ S2 @ U_a
    sym = lambda M: 0.5 * (M + M.T)
    H_a, S2_a = sym(H_a), sym(S2_a)

    print('\nReduction chain (orthogonal-AO Huckel limit, s=0, U=0):')
    print(f'  full Sz=0    dim = {N}')
    print(f'  A_1          dim = {U_a.shape[1]}')
    print(f'    H spectrum degeneracies: '
          f'{dict(sorted(deg_hist(np.linalg.eigvalsh(H_a)).items()))}')

    # --- singlet sub-block ----------------------------------------------
    ev_s2, vS = np.linalg.eigh(S2_a)
    US = vS[:, np.abs(ev_s2) < 1e-6]
    H_s = sym(US.T @ H_a @ US)
    print(f'  singlet-A_1  dim = {H_s.shape[0]}')
    print(f'    H spectrum degeneracies: '
          f'{dict(sorted(deg_hist(np.linalg.eigvalsh(H_s)).items()))}')
    print(f'    eigenvalues: {np.round(sorted(np.linalg.eigvalsh(H_s).tolist()), 4).tolist()}')

    # S^2 multiplet histogram on the A_1 block (total-spin labels kept)
    s2_hist = Counter(np.round(ev_s2, 4).tolist())
    print(f'\n  S^2 multiplet decomposition on A_1 (eigenvalue: multiplicity):')
    for ev, mult in sorted(s2_hist.items()):
        S_val = (np.sqrt(1 + 4 * max(ev, 0)) - 1) / 2
        print(f'    {ev:6.2f}  (S = {S_val:.1f}):  {mult}')

    # --- Hubbard diagonal check -----------------------------------------
    print('\nSanity check: Hubbard V_U diagonal on full basis, then project.')
    V_U = np.diag([double_occ(d) for d in det_strings]).astype(float)
    V_U_a = sym(U_a.T @ V_U @ U_a)
    V_U_s = sym(US.T @ V_U_a @ US)
    print(f'  [V_U, S^2] should be zero in A_1 block: '
          f'||.||_inf = {np.max(np.abs(V_U_a @ S2_a - S2_a @ V_U_a)):.2e}')

    # Ground state through the Hubbard PT: stays in singlet-A_1
    print('\nGround-state energies across U  (H = -sum + U*V_U, orthogonal AO):')
    for U in (0.0, 0.5, 1.0, 2.0, 5.0):
        H_tot = H_s + U * V_U_s
        e0 = np.linalg.eigvalsh(sym(H_tot))[0]
        print(f'  U = {U:4.1f}:  E_0 = {e0:.4f}')

    # --- explicit 8 singlet-A_1 basis vectors ---------------------------
    print('\n' + '=' * 72)
    print('The 8 singlet-A_1 linear combinations')
    print('=' * 72)
    print('\n12 orbits under C_5 + sigma_v  (rep det, orbit size, double-occ count):')
    reps = []
    for k, orb in enumerate(orbits):
        rep = det_strings[orb[0]]
        reps.append(rep)
        print(f'  [{k:2d}] {rep}   size={len(orb):2d}   doubly-occ={double_occ(rep)}')

    # Diagonalise H in the singlet block to label states by energy,
    # then pull each singlet vector back to the orbit (A_1) basis.
    ev, vec = np.linalg.eigh(H_s)
    singlet_in_A1 = US @ vec                # (12, 8)  orbit-basis coefficients

    print('\nCoefficients of each singlet-A_1 eigenstate over the 12 orbits:')
    print('(rows = orbits above, columns = eigenstates sorted by energy)')
    header = '       ' + ''.join(f' |{i}> ({ev[i]:+.3f})'.rjust(14)
                                 for i in range(len(ev)))
    print(header)
    for k in range(12):
        row = f'  [{k:2d}]'
        for i in range(len(ev)):
            c = singlet_in_A1[k, i]
            row += f'  {c:+.4f}    ' if abs(c) > 1e-10 else '      .       '
        print(row)

    # Also dump the ground state written out det-by-det (100 dets collapsed
    # to the 12 orbit reps with explicit weights).
    print('\nGround-state |0> written as an orbit expansion:')
    print(f'  E_0 = {ev[0]:+.6f}')
    for k in range(12):
        c = singlet_in_A1[k, 0]
        if abs(c) < 1e-8:
            continue
        # coefficient on each det in the orbit (uniform, 1/sqrt(size))
        per_det = c / np.sqrt(len(orbits[k]))
        print(f'  {c:+.4f} * orbit[{k}] ({reps[k]}, size {len(orbits[k])})'
              f'    [per det: {per_det:+.4f}]')


if __name__ == '__main__':
    main()
